# Generated by Django 6.0.7 on 2026-07-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0002_persondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='default/zw.png', null=True, upload_to='images/'),
        ),
    ]
