# Generated by Django 6.0.7 on 2026-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0004_alter_person_image_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, default='default/default_video.mp4', null=True, upload_to='video/'),
        ),
    ]
