# Generated by Django 6.0.7 on 2026-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0005_product_date_added_product_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
