# Generated by Django 6.0.7 on 2026-08-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0011_personhonorskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格(元)'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信单号')),
                ('total_fee', models.IntegerField(verbose_name='金额(分)')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已关闭')], default=0)),
                ('code_url', models.CharField(blank=True, max_length=512)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qml_webs.product')),
            ],
            options={
                'verbose_name': '订单',
            },
        ),
    ]
