# Generated by Django 6.0.7 on 2026-08-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0012_product_price_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='out_trade_no',
            new_name='order_no',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='价格(元)'),
        ),
    ]
