# Generated by Django 6.0.7 on 2026-08-15 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qml_webs', '0013_rename_out_trade_no_order_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
